# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - "*"
    exclude:
    - upstream/*


pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self

- script: make
  displayName: 'build network measure environment'
  
- script: cd /home ; sudo wget https://github.com/OpenNetLab/OpenNetLab-P2P-Measurment/blob/v-wangyif/bwpitch/machines.json 
  displayName: 'make network measure environment'

- script: docker run -v /home:/app -w /app --net=host --name net_evals net-env:latest python3 /home/onl/bwmur/bwmursever.py && docker run -v /home:/app -w /app --net=host --name net_evalc net-env:latest python3 /home/onl/bwmur/bwmurclient.py
  displayName: 'Run test'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'Pterosaur (1)'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    tagSource: manual
    tag: $(Build.BuildNumber)
    title: alphartc
    assets: '$(System.DefaultWorkingDirectory)/alphartc.tar.gz'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
  displayName: "Release target"

- script: docker image tag net-env:latest $(dockerRegistry)/net-env:latest
  displayName: 'Tag network environment image'

- task: Docker@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerRegistry: 'opennetlab Azure registry'
    repository: 'net-env'
    command: 'push'
    tags: 'latest'
  displayName: "Push net-env image"
